# SPDX-FileCopyrightText: 2025 Ben Jarvis
#
# SPDX-License-Identifier: Unlicense

title: libevpl
description: libevpl documentation
theme: just-the-docs
color_scheme: dark


url: https://chimeraproject.io/libevpl

aux_links:
  GitHub: https://github.com/chimera-nas/libevpl

plugins:
  - jekyll-sitemap
